#services:
#  mongodb:
#    image: mongo
#    container_name: mongo_db
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=veekshith
#      - MONGO_INITDB_ROOT_PASSWORD=veekshith
#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=veekshith
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=veekshith
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  mongo: {}


#services:
#  mongodb:
#    image: mongo
#    container_name: mongo_db
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=admin1123
#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin1123
#      - ME_CONFIG_MONGODB_SERVER=mongodb+srv://admin:admin1123@cluster0.dp01ztl.mongodb.net/
#volumes:
#  mongo: {}