

#spring:
#  application:
#    name:xchat
#  data:
#    mongodb:
#      username: veekshith
#      password: veekshith
#      host: localhost
#      port: 27017
#      database: chat_app
#      authentication-database: admin
#server:
#  port: 8088


spring:
  profiles:
    active: prod